n = int(input('digite um número: '))
print(' a tabuada do {} é: '.format(n))
print('='*20)
print('o numero {} x 1 é'.format(n), 1 * n)
print(2 * n)
print(3 * n)
print(4 * n)
print(5 * n)
print(6 * n)
print(7 * n)
print(8 * n)
print(9 * n)
print(10 * n)